# Generated by Django 5.2.8 on 2025-11-25 10:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_product_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='uuid',
            field=models.UUIDField("UUID", editable=False, default=uuid.uuid4)
        )
    ]
