# Generated by Django 5.2.8 on 2025-11-25 10:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_adding_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id'
        ),
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField("UUID", primary_key=True, editable=False, default=uuid.uuid4)
        )
    ]
